"""Initial migration.

Revision ID: 44484b76686a
Revises: 
Create Date: 2025-07-06 22:46:05.328743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44484b76686a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('openai_api_key', sa.String(length=128), nullable=True),
    sa.Column('hf_api_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('input_filename', sa.String(length=256), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('anonymised_text', sa.Text(), nullable=False),
    sa.Column('anonymisation_level', sa.String(length=16), nullable=False),
    sa.Column('model_used', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('user')
    # ### end Alembic commands ###
