"""Add model and level to ReportHistory with default

Revision ID: 7adcc7d0bfeb
Revises: 
Create Date: 2025-07-22 04:29:25.582457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adcc7d0bfeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_used', sa.String(length=50), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('anonymization_level', sa.String(length=50), server_default='unknown', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_history', schema=None) as batch_op:
        batch_op.drop_column('anonymization_level')
        batch_op.drop_column('model_used')

    # ### end Alembic commands ###
